server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # kompresi
    gzip on;
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_types text/plain text/css image/svg+xml application/javascript application/json;

    # halaman & berkas
    location / {
        try_files $uri $uri/ =404;
    }

    # cache aset statis 1 hari
    location ~* \.(svg|png|jpe?g|ico|js|css|woff2?)$ {
        add_header Cache-Control "public, max-age=86400";
        try_files $uri =404;
    }

    # jangan bocorkan versi nginx
    server_tokens off;
}
